spring:
  application:
    name: luminar-ledger

  datasource:
    url: jdbc:postgresql://localhost:5432/luminar_ledger
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 64
      minimum-idle: 8
      connection-timeout: 5000

  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    clean-disabled: true
